### PR TITLE
integrated webpack-dashboard

### LINKED ISSUE #49: Add webpack dashboard
It'd be nice to have a cool CLI dashboard for verifying status of the application within the terminal. 

Reference: https://github.com/FormidableLabs/webpack-dashboard

### PR DESCRIPTION
**Pull request by divyanshutomar**
Closes #49

### CODE REVIEW

**Comment by naveenkumarsangi** [comment]
Hi. Thanks for contributing to PiZilla! :tada:

(Powered by [GitMate.io](https://gitmate.io))

**Comment by naveenkumarsangi** [comment]
@divyanshutomar, please check for the failing travis CI build.

**Comment by naveenkumarsangi** [comment]
Uhm, could you please squash your commits together, @divyanshutomar? Because it's only a minor change to the original codebase.

**Comment by divyanshutomar** [comment]
@nkprince007 Done 👍

**Comment by naveenkumarsangi** [comment]
ack 
https://github.com/NITDgpOS/PiZilla/pull/72/commits/43dbbe8c417cede78e77d558bf56351f2d2cd2eb

**Pull request merged**
