### PR TITLE
Fixed issue #34-Add screenshots to readme

### PR DESCRIPTION
**Pull request by pranay414**
added screenshots to readme

### CODE REVIEW

**Review by naveenkumarsangi — CHANGES_REQUESTED** [review]
I see that you've added screenshot files but haven't linked them to README.md. Please add a new section by the name `Screenshots` and link the images there.

**Comment by pranay414** [comment]
@nkprince007 yes doing it

**Comment by pranay414** [comment]
@nkprince007 please review again.

**Review by naveenkumarsangi — APPROVED** [review]

**Comment by naveenkumarsangi** [comment]
@pranay414 Please rebase this merge request so that it can be merged.

**Comment by pranay414** [comment]
@nkprince007 done, please review again.

**Comment by naveenkumarsangi** [comment]
No, no, no! I've asked for a rebase. Not a merge commit. Merge commits destroy version history. @pranay414 please refer https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase if you don't understand what a rebase means.

**Comment by pranay414** [comment]
@nkprince007 please review again.

**Comment by naveenkumarsangi** [comment]
Change the commit log, please. Follow the structure shown below.

```
shortlog: basic description

detailed description

Fixes <issue url>
```

e.g. suppose your commit adds something in readme

```
README: Update sub title

Update the sub title with a detailed description of the test run.

Fixes https://github.com/nitdgpos/pizilla/123
```

**Comment by naveenkumarsangi** [comment]
Use `git commit --amend` to edit your commit message.

**Comment by pranay414** [comment]
@nkprince007 done.

**Comment by naveenkumarsangi** [comment]
Thanks for the work @pranay414.

Merged 🎉

**Comment by pranay414** [comment]
@nkprince007 Thank you for your help.

**Pull request merged**
