### PR TITLE
 Modify browser notifications to show which file was uploaded #71

### PR DESCRIPTION
**Pull request by JayjeetAtGithub**

### CODE REVIEW

**Comment by JayjeetAtGithub** [comment]
Why is the nodejs 6 build failing ?

**Comment by naveenkumarsangi** [comment]
It is alright now. Guess it is some non-deterministic network failure on the CI server.

**Comment by naveenkumarsangi** [comment]
Please squash all your commits together so that it can be merged.

**Comment by JayjeetAtGithub** [comment]
Okk sure...will get it done by tonight

**Comment by JayjeetAtGithub** [comment]
@nkprince007 squashed the 3 commits in a single commit and travis build successfull.Pls review

**Comment by JayjeetAtGithub** [comment]
Thanks a lot ... Which next issue of PiZilla should i work on?

**Comment by Compro-Prasad** [comment]
Find it yourself

**Pull request merged**
